# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{path_rewriter}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sunteya"]
  s.date = %q{2010-04-06}
  s.email = %q{Sunteya@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "depends.rb",
     "lib/path_rewriter.rb",
     "lib/path_rewriter/rails.rb",
     "lib/path_rewriter/url_codec.rb",
     "path_rewriter.gemspec",
     "spec/path_rewriter/url_codec_spec.rb",
     "spec/path_rewriter_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sunteya/path_rewriter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{rewrite rails generate url and route.}
  s.test_files = [
    "spec/path_rewriter/url_codec_spec.rb",
     "spec/path_rewriter_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gem_loader>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 2.3.5"])
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<gem_loader>, [">= 0.2.0"])
      s.add_dependency(%q<actionpack>, ["~> 2.3.5"])
      s.add_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<gem_loader>, [">= 0.2.0"])
    s.add_dependency(%q<actionpack>, ["~> 2.3.5"])
    s.add_dependency(%q<addressable>, [">= 2.1.1"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

